# Generated by Django 2.2.5 on 2020-01-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ランキング'),
        ),
    ]
