# Generated by Django 2.2.5 on 2020-01-23 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200122_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='check',
            field=models.BooleanField(default=False, verbose_name='閲覧済'),
        ),
        migrations.AddField(
            model_name='movies',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='評価点'),
        ),
    ]
