# Generated by Django 2.2.5 on 2020-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200123_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='check',
            field=models.BooleanField(blank=True, default=False, verbose_name='閲覧済'),
        ),
    ]
