# Generated by Django 2.2.5 on 2020-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200123_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='あらすじ'),
        ),
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='公開日'),
        ),
        migrations.AddField(
            model_name='movies',
            name='time',
            field=models.TextField(blank=True, null=True, verbose_name='上映時間'),
        ),
    ]
