# Generated by Django 2.2.5 on 2020-01-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200131_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ジャンル', to='movies.Tag'),
        ),
    ]
